# Shell variables
# Generated by 'wal'
wallpaper="/home/edudscrc/archeva-01-dotfiles/hypr/wallpapers/eva4k.png"

# Special
background='#100c12'
foreground='#c3c2c3'
cursor='#c3c2c3'

# Colors
color0='#100c12'
color1='#6A4AA5'
color2='#8A7497'
color3='#8A5FE2'
color4='#8F63E7'
color5='#7897AE'
color6='#67CC82'
color7='#948d97'
color8='#65586c'
color9='#8d70c1'
color10='#ac7ec8'
color11='#ae9bd4'
color12='#b2a0d6'
color13='#8cb3ce'
color14='#93d1a4'
color15='#c3c2c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
