--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/edudscrc/archeva-01-dotfiles/hypr/wallpapers/eva4k.png"

-- Special
background="#100c12"
foreground="#c3c2c3"
cursor="#c3c2c3"

-- Colors
color0="#100c12"
color1="#6A4AA5"
color2="#8A7497"
color3="#8A5FE2"
color4="#8F63E7"
color5="#7897AE"
color6="#67CC82"
color7="#948d97"
color8="#65586c"
color9="#8d70c1"
color10="#ac7ec8"
color11="#ae9bd4"
color12="#b2a0d6"
color13="#8cb3ce"
color14="#93d1a4"
color15="#c3c2c3"
